export default {
  //
  tranke: [
    {
      id: 0,
      name: 'Manatrank der Küste',
      bild: 'statics/Tränke/manatrank_der_küste.jpg',
      beschreibung: 'Stellt 11084 Mana wieder her. (1 Min Abklingzeit)',
      zutat1: 'Flussknospe: 3 oder 2 davon!',
      zutat1bild: 'statics/Tränke/flussknospe.jpg',
      zutat2: 'Kristallphiole: Einmal oder so',
      zutat2bild: 'statics/Tränke/kristallphiole.jpg',
    },
    {
      id: 1,
      name: 'Heiltrank der Küste',
      bild: 'statics/Tränke/heiltrank_der_küste.jpg',
      beschreibung: 'Stellt 33251 Gesundheit wieder her. (1 Min Abklingzeit)',
      zutat1: 'Sirenenpollen: 3 oder 2 davon!',
      zutat1bild: 'statics/Tränke/sirenenpollen.jpg',
      zutat2: 'Kristallphiole: Einmal oder so',
      zutat2bild: 'statics/Tränke/kristallphiole.jpg',
    },
    {
      id: 2,
      name: 'Fläschchen der unendlichen Tiefe',
      bild: 'statics/Tränke/flask_unendlichen_tiefe.jpg',
      beschreibung: 'Erhöht die Intelligenz 1 Stunde lang um 238. Gilt sowohl als Kampfelixier als auch als Wächterelixier. Dieser Effekt hält über den Tod hinaus an. (3 Sek. Abklingzeit)',
      zutat1: '',
      zutat1bild: '',
      zutat2: '',
      zutat2bild: '',
    },
    {
      id: 3,
      name: 'Fläschchen der Ströme',
      bild: 'statics/Tränke/flask_der_ströme.jpg',
      beschreibung: 'Erhöht die Beweglichkeit 1 Stunde lang um 238. Gilt sowohl als Kampfelixier als auch als Wächterelixier. Dieser Effekt hält über den Tod hinaus an. (3 Sek. Abklingzeit)',
      zutat1: '',
      zutat1bild: '',
      zutat2: '',
      zutat2bild: '',
    },
    {
      id: 4,
      name: 'Fläschchen des Tiefensogs',
      bild: 'statics/Tränke/flask_tiefensogs.jpg',
      beschreibung: 'Erhöht die Stärke 1 hour lang um 238. Gilt sowohl als Kampfelixier als auch als Wächterelixier. Dieser Effekt hält über den Tod hinaus an. (3 Sek. Abklingzeit)',
      zutat1: '',
      zutat1bild: '',
      zutat2: '',
      zutat2bild: '',
    },
    {
      id: 5,
      name: 'Fläschchen des weiten Horizonts',
      bild: 'statics/Tränke/flask_weiten_horizonts.jpg',
      beschreibung: 'Erhöht die Ausdauer 1 hour lang um 357. Gilt sowohl als Kampfelixier als auch als Wächterelixier. Dieser Effekt hält über den Tod hinaus an. (3 Sek. Abklingzeit)',
      zutat1: '',
      zutat1bild: '',
      zutat2: '',
      zutat2bild: '',
    },
    {
      id: 6,
      name: 'Mystischer Kessel',
      bild: 'statics/Tränke/mystischer_kessel.jpg',
      beschreibung: 'Stellt einen Kessel her, der von Schlachtzugsmitgliedern benutzt werden kann, um an die Boni eines Fläschchens entsprechend ihrer Klasse und Talente zu gelangen. Der Kessel enthält 30 Anwendungen und bleibt 10 min lang bestehen.',
      zutat1: 'Fläschchen der unendlichen Tiefe: 4 Stück',
      zutat1bild: 'statics/Tränke/flask_unendlichen_tiefe.jpg',
      zutat2: 'Fläschchen der Ströme: 4 Stück',
      zutat2bild: 'statics/Tränke/flask_der_ströme.jpg',
    },
  ],
  bestellung: [
    {
      id: 0,
      name: 'txs',
      beschreibung: 'du xxxxxd so.',
    },
  ],
};
